---
- name: reset | kubeadm reset
  command: kubeadm reset
  ignore_errors: true

- name: reset | stop and disable services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - kubelet
    - etcd
    - docker
  ignore_errors: true

- name: reset | remove services
  file:
    path: "/etc/systemd/system/{{ item }}.service"
    state: absent
  with_items:
    - etcd

# - name: reset | gather mounted kubelet dirs
#   shell: mount | grep /var/lib/kubelet | awk '{print $3}'
#   check_mode: no
#   register: mounted_dirs
#   tags:
#     - mounts

# - name: reset | unmount kubelet dirs
#   command: umount {{item}}
#   with_items: '{{ mounted_dirs.stdout_lines }}'
#   tags:
#     - mounts

- name: unmount kubelet filesystem
  mount: path=/var/run/kubelet state=unmounted

- name: reset | uninstall package
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - kubeadm
    - kubectl
    - kubelet
    - kubernetes-cni
    - docker-engine

- name: reset | systemctl daemon-reload
  command: systemctl daemon-reload

- name: reset | systemctl reset-failed
  command: systemctl reset-failed

- name: flush iptables
  iptables:
    flush: yes
  ignore_errors: true

- name: cleanup networks
  shell: "ip link del flannel.1; ip link del cni0;"
  ignore_errors: true

- name: reset | delete some files and directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/kubernetes
    - /etc/systemd/system/kubelet.service.d
    - /etc/systemd/system/docker.service.d
    - /etc/docker
    - /etc/yum.repos.d/k8s.repo
    - /var/lib/kubelet
    - /var/lib/docker
    - /root/.kube
    - /var/lib/etcd
    - /etc/ssl/etcd
    - /etc/etcd.env
    - /etc/cni
    - /etc/nginx
    - /opt/cni
    - /var/log/pods
    - /usr/local/bin/etcd
    - /usr/local/bin/etcdctl
    - /usr/local/bin/cfssl
    - /usr/local/bin/cfssljson
    - /usr/local/bin/cfssl-certinfo
    - /run/xtables.lock
    - /run/flannel
    - /run/kubernetes

- name: reset | Restart network
  service:
    name: "{{item}}"
    state: restarted
  with_items:
    - network
    - networking
  args:
    warn: false
  ignore_errors: true

- name: reset | remove host entries from /etc/hosts
  blockinfile:
    path: "/etc/hosts"
    state: absent
    follow: yes
    marker: "# Ansible inventory hosts {mark}"