---
- include: verify-settings.yml
  tags:
    - asserts

- name: Assign inventory name to hostnames
  hostname:
    name: "{{inventory_hostname}}"

- include: etchosts.yml
  tags:
    - etchosts

- include: centos.yml
  when: ansible_distribution in [ 'CentOS','RedHat']

- name: Create kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  when: inventory_hostname in (groups['kube-master'] + groups['kube-node']+ groups['etcd']|default([]))|unique
  tags:
    - kubelet
  with_items:
    - "/etc/kubernetes"
    - "/etc/kubernetes/pki"
    - "/etc/kubernetes/manifests"
    - "/etc/kubernetes/ssl/etcd"


- name: Create cni directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  with_items:
    - "/etc/cni/net.d"
    - "/opt/cni/bin"
  when:
    - inventory_hostname in (groups['kube-master'] + groups['kube-node']+ groups['etcd']|default([]))|unique
  tags:
    - network

- name: Ensure Yum repository
  become: yes
  yum_repository:
    name: kubernetes
    description: kubernetes Repository
    baseurl: "{{aliyun_k8s_yum_repo}}"
    enabled: no
    gpgcheck: no
    state: present

- name: Download cfssl
  get_url:
    url: "{{nginx_file_service}}/cfssl/cfssl_linux-amd64"
    dest: /usr/local/bin/cfssl
    mode: 0755
  when: inventory_hostname in (groups['kube-master'] + groups['etcd']|default([]))|unique
  environment:
    http_proxy: "{{ http_proxy| default ('') }}"
    https_proxy: "{{ https_proxy| default ('') }}"
    no_proxy: "{{ no_proxy| default ('') }}"

- name: Download cfssljson
  get_url:
    url: "{{nginx_file_service}}/cfssl/cfssljson_linux-amd64"
    dest: /usr/local/bin/cfssljson
    mode: 0755
  when: inventory_hostname in (groups['kube-master'] + groups['etcd']|default([]))|unique
  environment:
    http_proxy: "{{ http_proxy| default ('') }}"
    https_proxy: "{{ https_proxy| default ('') }}"
    no_proxy: "{{ no_proxy| default ('') }}"

- name: Download cfssl-certinfo
  get_url:
    url: "{{nginx_file_service}}/cfssl/cfssl-certinfo_linux-amd64"
    dest: /usr/local/bin/cfssl-certinfo
    mode: 0755
  when: inventory_hostname in (groups['kube-master'] + groups['etcd']|default([]))|unique
  environment:
    http_proxy: "{{ http_proxy| default ('') }}"
    https_proxy: "{{ https_proxy| default ('') }}"
    no_proxy: "{{ no_proxy| default ('') }}"